### ISSUE TITLE
Training on HVG genes only without subsetting

### ISSUE THREAD

**Issue by mxposed** [scverse/scvi-tools#1489]
Hi

I wonder if I missed this, but is there a way to train on HVG subset of genes, and keep the other genes in the object also?
The tutorial https://docs.scvi-tools.org/en/stable/tutorials/notebooks/api_overview.html implied `subset=True` in `highly_variable_genes` call, and I couldn't find the parameters for `setup_anndata` or `train` that would allow subsetting the genes to HVG subset only.

If there's no such this, but you agree it'd be nice, I'm happy to open a pull request.

Why I'm asking? Because right now using anndata is quirky: you can save all genes in the `raw` of the object, but there is only one matrix there (`X`) and it is expected to be normalized (log-normalized) counts, for running scanpy differential gene expression and plotting. So the integer counts go to `layers` but if we subset to HVGs, then we lose the count layer for non-HVGs.

Thanks

**Comment by adamgayoso** [comment]
There is no way currently. We considered it at the beginning of scvi-tools, but there is overhead in subsetting the object (either on the fly, or cache the subset version behind the scenes). 

I do agree anndata is quirky in this regard. I would suggest you try using mudata, where modalities there would correspond to subsetted and non subsetted data. This would allow you to avoid using .raw. Muon also has some nice plotting functions so that you can plot from one modality or the other.

Then, if you use mudata, you'd effectively be giving scvi-tools `mdata.mod["hvg"]` as input

**Comment by mxposed** [comment]
Thank you! I'll close this then, since this is not planned for `scvi-tools`
I'll look at mudata, haven't heard of it, thank you

**Comment by adamgayoso** [comment]
@mxposed see https://mudata.readthedocs.io/en/latest/

Basically it's a collection of anndata objects
