### ISSUE TITLE
View setup args to return a dictionary

### ISSUE THREAD

**Issue by LuckyMD** [scverse/scvi-tools#1611]
When setting up reference mapping, it is very useful to be able to check that the query data is formatted correctly. This requires knowledge of how the reference model was set up (info from `model.adata_manager.registry`). However, I only seem to be able to load the full model while also passing the AnnData object in the correct format (note: why is this needed?). The other way to get to this information is via `scvi.model.SCANVI.view_setup_args`, however this only prints the output to the screen and thus requires a context manager to capture and parse that output. It would be super useful if this function just output a dictionary.

Ideal solution: 
A dictionary return object for `view_setup_args()`.

**Comment by watiss** [comment]
I added a pr to hopefully address what you're looking for.

Good question as to why an anndata object is needed during model load. One of the reasons is that most model functionalities would not function without a valid adata. However, I agree that there should be a way to use the model weights (and possibly even other things such as latent embeddings) without requiring access to the full anndata object. In fact, I find myself needing this right now for the scvi model zoo project where we want to get information out of the model without having access to the full anndata. I dont see why this can't be implemented, it just isn't yet (the model methods that absolutely require an anndata to function would just error out).

**Comment by LuckyMD** [comment]
Firstly: thanks, Valeh! 

Secondly, yes, exactly! I'm also trying to make a query mapping (and therefore the reference model) as lightweight as possible. If the model can be loaded without the training anndata for prep_query_data, then why not otherwise? I looked into code a bit for what's being done for the prep_query_data function, but then didn't want to go too deep down the rabbit hole ^^.

**Comment by watiss** [comment]
Hi Malte. Reading your message again, I _think_ (correct me if I'm wrong) that you are looking to call `prepare_query_anndata` with a query adata and a reference model, is that right? In that case, you don't actually need the training data. You have two options:

1. Pass the _path_ to your model (no training data required) as part of the `reference_model` parameter of the `prepare_query_anndata` call. We'll take care of loading what we need from the model file and don't require the training adata.
2. Load the model by calling the `load` method and passing in your _query_ adata (the same that you're passing into `prepare_query_anndata`. Once again, no training data is required.

I would go for option 1 since it is the simplest.
