### ISSUE TITLE
The Kernel crashed while executing training model

### ISSUE THREAD

**Issue by sailseem** [scverse/scvi-tools#1783]
Dear developers,

This is really good package and useful tools for scRNA-seq analysis. But I found it's kinda hard to train the model on M1 Mac.
Every time I execute model.train(), returned like this;

The Kernel crashed while executing code in the the current cell or a previous cell. Please review the code in the cell(s) to identify a possible cause of the failure. Click [here](https://aka.ms/vscodeJupyterKernelCrash) for more info. View Jupyter log for further details.
Canceled future for execute_request message before replies were done

Can you help me with this? I do appreciate your valuable time.
Thanks

**Comment by adamgayoso** [comment]
Can you provide any traceback and versions of software you are using? Are you using use_gpu=True?

**Comment by hejian41** [comment]
Same issue. I guess it is due to the memory limit set in jupyterlab. If I run the code in python envs directly, the kernel didn't crash but proceed very slowly.  GPU seems not be used here.

![image](https://user-images.githubusercontent.com/38309419/211030673-de553ecf-0606-42dc-b654-1b65af40dfdb.png)

**Comment by adamgayoso** [comment]
Closing as this issue is now stale. If there are future problems please reach out on our discourse forum.
