### ISSUE TITLE
Global seed always set to 0 on import of scvi

### ISSUE THREAD

**Issue by thomasgaudelet** [scverse/scvi-tools#1883]
The global seed is always reset to 0 when import scvi in a package due to this line 

https://github.com/scverse/scvi-tools/blob/0b820b2e3ca9dd3f4ef91d1c9016542371a4856b/scvi/_settings.py#L230

This is an issue in integration whereby in some scenario the seed set by a user is overriden by default scvi seed.

```python
import scvi
```

```pytb
Global seed set to 0
```

#### Versions:

> VERSION 0.19.0

**Comment by adamgayoso** [comment]
Can you describe the fix you'd like to see?

You can always set the seed after import using `scvi.settings.seed = MY_SEED`

**Comment by thomasgaudelet** [comment]
Would it be possible to not set a default seed on import? 
For instance, by removing `self.seed = seed` from the initialisation of `ScviConfig` class (or changing setter and default). 
The user should really be setting it if they want to or if they haven't set it already elsewhere.

**Comment by aribenjamin** [comment]
I agree; I also wasn't expecting this behavior. This is a global seed, affecting Numpy as well. I just ran into this bug; at the top of my script I had set a random integer via `rand_id = np.random.randint(1000000)` that I had planned to use for saving each model to a unique filename. Because of this deterministic setting, `rand_id` is identical each time. 

Since I can't just set `MY_SEED` to something else (deterministically), I'm needing to set it with another external source of randomness, e.g. `scvi.settings.seed = secrets.randbelow(100000)`.

**Comment by adamgayoso** [comment]
Ok we can disable this, but we need to add a warning at import that the behavior was removed and to manually set it.

@martinkim0 perhaps we can deprecate this in 0.20.2 for the 1.0 release

**Comment by cane11** [comment]
I think default deterministic behavior is actually a good feature. Can we set it to 0 as default and if set to None generate a random seed?

**Comment by adamgayoso** [comment]
I think it's good to use the convention of other packages where you have to manually set the seed yourself. We should just include `scvi.setttings.seed` in all tutorials.

**Comment by thomasgaudelet** [comment]
I agree. I would add that default setting might be fine when using scvi in isolation, but when integrated in a package, this can have undesired effects, for instance replacing user settings. It took me some times to figure out that there was a default seed setting on import of scvi. In general, I think it's good practice to leave it up to the user to avoid these scenarios.
