### ISSUE TITLE
JAX issue

### ISSUE THREAD

**Issue by anhducnguyen0122** [scverse/scvi-tools#2216]
I was able to install ```scvi-tools``` via ```conda``` just fine, but when I import the module, it returns this error

```pytb
cannot import name 'ShapedArray' from 'jax'
```

#### Versions:

scvi-tools = 1.0.2
jax = 0.4.14

**Comment by martinkim0** [comment]
Hi, this issue is originating from `flax` since it looks like the package is not being updated correctly on [conda](https://anaconda.org/conda-forge/flax) (latest on conda is 0.6.1 but latest on pypi is 0.7.0). For now, this can be fixed by installing via pip:
```
pip install -U scvi-tools
```
and we'll find a fix for the conda installation in our next patch (1.0.3). Hope this helps!

**Comment by anhducnguyen0122** [comment]
@martinkim0 Thanks. I installed the old version and it worked. I will look out for the new release

**Comment by maarten-devries** [comment]
I also needed `pip install -U flax`
