### ISSUE TITLE
'SCVI' object has no attribute 'eval'

### ISSUE THREAD

**Issue by FZ-hajji** [scverse/scvi-tools#2740]
Hello ,

I used the following code to save and load scvi model: 
model.save("my_model/")
model = scvi.model.SCVI.load("my_model/", adata=adata)
model.eval()

But when I apply eval() to the model I get this error:
'SCVI' object has no attribute 'eval'

**Comment by martinkim0** [comment]
Hi, this is because `SCVI` is not an instance of `torch.nn.Module`. For this, you would need to call `model.module.eval`. However, this is not necessary in this case as we already call `eval` in our `load` function [here](https://github.com/scverse/scvi-tools/blob/main/src/scvi/model/base/_base_model.py#L717).

**Comment by FZ-hajji** [comment]
Thank you so much
