### ISSUE TITLE
The scrna_raw_counts_properties method has an error in the calculation method of the raw_normalized_mean2 field, causing the raw_normalized_mean2 indicator to be invalid.

### ISSUE THREAD

**Issue by raozuming** [scverse/scvi-tools#2792]
**Is your feature request related to a problem? Please describe.**

np.asarray(data.sum(axis=1)).ravel().reshape(-1, 1) has 0 elements in the matrix, causing the raw_normalized_mean2 field calculation to fail.
**Describe the solution you'd like**

raw_normalized_mean2 is calculated correctly

**Comment by canergen** [comment]
Hi, thank you for reporting it. First question: I assume correctly that you don’t get incorrect values but you get a ValueError as you have a shape mismatch. This is happening during construction of the pandas.DataFrame. Can you copy the exact error message? It should happen for raw_normalized_mean but also the two other means in the function (or are your size factors zero?)

**Comment by raozuming** [comment]
RuntimeWarning: divide by zero encountered in divide
  scaling_factor = 1 / np.asarray(data.sum(axis=1)).ravel().reshape(-1, 1)

**Comment by canergen** [comment]
This means that your data contains cells without any count. Is it meaningful for your model to input cells without counts (I assume it’s due to your highly variable gene selection)? I would highly recommend to filter to min_counts before training the model as otherwise training might be unstable.
@martinkim0 We could add a check and print a warning when setting up a model if cells contain less than let’s say 30 counts.

**Comment by raozuming** [comment]
Thanks
