### ISSUE TITLE
Device management

### ISSUE THREAD

**Issue by canergen** [scverse/scvi-tools#2992]
1. Use TOTALVI.train(accelerator = 'cpu', devices = 1), the program detects the GPU environment, and still uses the GPU for training. As shown in the figure below, due to my GPU driver, the GPU reports an error, indicating that the program still uses GPU resources for training instead of CPU resources
![30F79B4C-0EEC-47af-B4FF-9B3CE725E988](https://github.com/user-attachments/assets/7effd33d-2c09-4723-a5f0-44516ab24c87)

2. How to use multi-core CPU for model training

_Originally posted by @raozuming in https://github.com/scverse/scvi-tools/issues/2889#issuecomment-2367582829_

**Comment by canergen** [comment]
Please don't post issues that are unrelated. Especially not in releases. Torch uses by default multiple workers. I can't reproduce that using accelerator='cpu' doesn't disable the GPU. Which version of scvi-tools are you using? You can also set cuda visible devices to `os.environ["CUDA_VISIBLE_DEVICES"]=""` at the top of your script. Lastly, I would not recommend installing a CUDA version of torch and don't install correct drivers and would recommend updating CUDA drivers to a more recent version.

**Comment by raozuming** [comment]
@canergen 
Hello, I use the code from the main branch. Since the use_gpu parameter in TOTALVI.train() is cancelled, I have to use the accelerator and devices parameters to replace the previous functions. However, according to the maintainer, accelerator='cpu', devices=1 will schedule CPU resources for model training, but I cannot implement it at present.
![9E62E543-62F1-4989-A9CE-CEE7D73B37D8](https://github.com/user-attachments/assets/84f064f5-6d37-4699-b8f1-020dd614a7cb)

**Comment by canergen** [comment]
It will train using the CPU (you can see in your screenshot that it is correctly set). However, you are using a broken CUDA (outdated) and torch tries using CUDA as it’s installed with CUDA support. This doesn’t work. Please fix your CUDA or reinstall torch without CUDA support. I highlighted above ways to fix it. Please follow those.

**Comment by raozuming** [comment]
Thanks

**Comment by canergen** [comment]
Assuming it’s fixed.
